version: 0.2

batch:
  fast-fail: false
  build-fanout:
    parallelism: 2

phases:
  install:
    commands:
      - echo 'Installing Elixir dependencies'
      - sudo apt update
      - sudo DEBIAN_FRONTEND=noninteractive apt install -y elixir
      - elixir --version
      - mix --version
  pre_build:
    commands:
      - echo 'Prebuild'
  build:
    commands:
      - echo 'Running Elixir Tests'
      - codebuild-tests-run --test-command 'mix test' --files-search "codebuild-glob-search '**/test/**/*_test.exs'" --sharding-strategy 'equal-distribution'
  post_build:
    commands:
      - echo "Would deploy here"
